# https://projecteuler.net/problem=2
# Even Fibonacci Numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13,21,34,55,89,...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# FINAL RESULT: 4613732

import time
startTime = time.time()
firstNum, secondNum = 0, 1
result = 0
# fibonacci = {0}

while result < 4000000:
    # fibonacci.add(firstNum)
    if firstNum %2 == 0:
        result = result + firstNum
    firstNum, secondNum = secondNum, firstNum + secondNum

# print(fibonacci)
print(result)
print(f"Time: {time.time()-startTime} s")
